In [2]:
import pandas as pd

In [ ]:
df = pd.read_excel("airqualitytrendsbycity2000-2023.xlsx")


df = df.drop(df.columns[0], axis=1)
df.head()

,"Through a combination of regularly scheduled technical systems audits of non-EPA laboratories processing state PM2.5 monitoring data and additional assessments of data quality, EPA has identified data quality issues that affect Florida, Illinois, most of Tennessee and parts of Kentucky. EPA has made a preliminary determination that this data should not be used for regulatory purposes. Until a final determination has been made, EPA has moved the data in the Air Quality System database for the PM2.5 sites in question from parameter code 88101 (PM2.5 at local conditions; used for regulatory data) to parameter code 88501 (PM2.5 raw data). This change will clarify to data users that data from these sites should not be compared to the PM2.5 National Ambient Air Quality Standards until EPA has made a final validity determination. This data is not included in the PM2.5 trends assessment or this summary table.",Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,...,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28
0,Air Quality Trends by City 2000-2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Note: The values shown are the composite aver...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,CBSA,Pollutant,Trend Statistic,Number of Trends Sites,2000.000,2001.000,2002.000,2003.000,2004.000,2005.000,...,2014.000,2015.000,2016.000,2017.000,2018.000,2019.000,2020.000,2021.000,2022.000,2023.000
3,10300,O3,4th Max,1,0.082,0.086,0.089,0.088,0.074,0.082,...,0.068,0.065,0.069,0.066,0.071,0.059,0.067,0.066,0.065,0.071
4,10420,O3,4th Max,2,0.085,0.096,0.100,0.090,0.079,0.091,...,0.060,0.065,0.060,0.066,0.068,0.062,0.063,0.067,0.070,0.071